services:
  - type: web
    name: divine-digita-forum
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        value: postgresql://forum_db_sdxl_user:tz3gKDwCxFp0JcK0FPiQ87AVP6YqIewJ@dpg-d4m5f9pr0fns739vgt0g-a.oregon-postgres.render.com/forum_db_sdxl
